# Generated by Django 5.0.1 on 2024-02-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_kitchen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_conformed',
            field=models.BooleanField(default=False),
        ),
    ]
