# Generated by Django 5.0.2 on 2024-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_conformed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
